# Generated by Django 4.2.4 on 2023-08-19 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='agent',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.agent'),
        ),
    ]
