# Generated by Django 4.2.4 on 2023-08-19 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_package_agent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='agent',
        ),
        migrations.RemoveField(
            model_name='package',
            name='destination',
        ),
        migrations.DeleteModel(
            name='Activity',
        ),
        migrations.DeleteModel(
            name='Package',
        ),
    ]
