# Generated by Django 4.2.4 on 2023-08-19 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_package_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.package'),
        ),
    ]
