# Generated by Django 4.2.4 on 2023-08-26 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_activity_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='is_top_package',
            field=models.BooleanField(default=False),
        ),
    ]
