# Generated by Django 4.2.4 on 2024-03-26 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_package_image_package_is_top_package'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='package',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images/packages/'),
        ),
        migrations.AddField(
            model_name='package',
            name='categories',
            field=models.ManyToManyField(to='app.category'),
        ),
    ]
