# Generated by Django 4.2.4 on 2024-03-26 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_rename_image_package_old_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='old_image',
            new_name='image',
        ),
    ]
