# Generated by Django 4.2.4 on 2024-03-26 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0013_rename_old_image_package_image"),
    ]

    operations = [
        migrations.RemoveField(model_name="activity", name="package",),
        migrations.AddField(
            model_name="activity",
            name="activity_package",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="package_activities",
                to="app.package",
            ),
        ),
        migrations.AddField(
            model_name="package",
            name="activities",
            field=models.ManyToManyField(to="app.activity"),
        ),
    ]
