# Generated by Django 4.2.4 on 2024-03-27 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_remove_activity_package_activity_activity_package_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='categories',
        ),
        migrations.AddField(
            model_name='package',
            name='category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.category'),
        ),
    ]
