# Generated by Django 4.2.4 on 2024-04-01 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_remove_package_end_date_remove_package_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='destination_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.destination'),
        ),
    ]
