# Generated by Django 4.2.4 on 2024-04-02 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_package_destination_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='day',
            new_name='day_number',
        ),
        migrations.RemoveField(
            model_name='package',
            name='activities',
        ),
    ]
