# Generated by Django 4.2.4 on 2024-04-02 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_rename_day_activity_day_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='day_number',
            new_name='day',
        ),
    ]
