# Generated by Django 4.2.4 on 2024-06-11 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='is_read',
        ),
    ]
